version: '3.1'

services:
  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mdb1
    networks:
      - nano-internal
  server:
    image: nano-express:1.1
    build: ./server
    restart: always
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      DB_URL: "mongodb://mongodb:27017/"
      DB_USER: root
      DB_PASS: mdb1
    ports:
      - "8085:2900"
    networks:
      - nano-internal
  client:
    image: nano-client:1.0
    build: 
      context: ./client
      args:
        - REACT_APP_API_URL=http://localhost:8085
    restart: always
    depends_on:
      - server
    ports:
      - "8086:5000"

networks:
  nano-internal:
    driver: bridge
